### ISSUE TITLE
[3.0.207][64bit] Surface pro 3 intel i5 - touch screen becomes unresponsive while using after 10-5 mins sometimes less 

### ISSUE THREAD

**Issue by vtapping** [JideTechnology/Remix-OS-For-PC#82] opened 2017-02-20 20:21 UTC
While using remix is on surface pro 3 the touch screen just freezes. It will only work if I attach the keyboard or I would have to restart the device.

**Comment by Neurovert** [comment] 2017-03-14 21:02
Duplicate of #58

**Closed as completed by Neurovert** 2017-03-14 21:02 UTC
Labels: bug, drivers, touch
