### ISSUE TITLE
[3.0.207][32-bit] Display Issue

### ISSUE THREAD

**Issue by marbledash1** [JideTechnology/Remix-OS-For-PC#66] opened 2017-01-12 19:17 UTC
I am having a display problem when I move mouse the screen flickers part of screen is black performance is good on remix but the screen is filickering so bad that it makes it unusable. Running remix OS 32-bit version 3.0.207. Also when I check for updates nothing shows up. I have installed remix using windows installer dual boot with windows 10 32-bit and remix os.
Specs are
Toshiba Satellite A215-S5808
CPU- AMD Athlon 64 X2 TK-55 / 1.8 GHz
Ram-2gb ddr2
GPU- ATI Radeon xpress X1200
Issue is not present in windows 10 32-bit just remix has the display problem part of the screen goes black and flickers when moving mouse please fix.

SCHEME FOR COMMENT

Steps to reproduce the problem: Moving mouse around.

Correct behaviour should be: No screen flickering and all of screen should be visible at all times.

Images, videos showing problem: here is a video I took that recreates the problem https://youtu.be/b6GBP7WXYK8

Logs:

**Comment by Neurovert** [comment] 2017-01-16 17:19
Duplicate of #65

**Closed as completed by Neurovert** 2017-01-16 17:19 UTC
Labels: duplicate
